# nvfetcher.toml
[waybar-mpris]
src.git = "https://git.hrfee.pw/hrfee/waybar-mpris"
fetch.git = "https://git.hrfee.pw/hrfee/waybar-mpris.git"
[sddm-sugar-candy]
src.git = "https://github.com/eekrain/sddm-sugar-candy"
fetch.github = "eekrain/sddm-sugar-candy"
[my-custom-fonts]
src.manual = "1.0"
fetch.url = "https://github.com/eekrain/dotfiles/releases/download/1.0/my_custom_fonts.tar.xz"
[materialyoucolor]
src.pypi = "materialyoucolor"
fetch.pypi = "materialyoucolor"
[helium]
src.manual = "0.6.3.1"
fetch.url = "https://github.com/imputnet/helium-linux/releases/download/0.6.3.1/helium-0.6.3.1-x86_64.AppImage"