# nvfetcher.toml
[waybar-mpris]
src.git = "https://git.hrfee.pw/hrfee/waybar-mpris"
fetch.git = "https://git.hrfee.pw/hrfee/waybar-mpris.git"
[sddm-sugar-candy]
src.git = "https://github.com/eekrain/sddm-sugar-candy"
fetch.github = "eekrain/sddm-sugar-candy"
[my-custom-fonts]
src.manual = "1.0"
fetch.url = "https://github.com/eekrain/dotfiles/releases/download/1.0/my_custom_fonts.tar.xz"
[python-materialyoucolor]
src.pypi = "materialyoucolor"
fetch.pypi = "materialyoucolor"
